# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wallpapers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wallpapers

	pod 'RAMAnimatedTabBarController', "~> 2.0.13" 

pod ‘Kingfisher’, ‘~> 3.0’
pod ‘lottie-ios’
pod "SAParallaxViewControllerSwift"
pod "SwiftSpinner"
pod "LIHAlert"
pod 'FaveButton', '~> 2.0.3'


end
